#!/usr/bin/env node
/**
 * sync-tokens — regenerate `src/styles/palette.css` (the raw colour ramps) from the
 * E.ON Figma colour variables. Run: `npm run sync:tokens`.
 *
 * Source of variables (in priority order):
 *   1. Figma Variables REST API — if `FIGMA_TOKEN` is set. The proper CI/headless path,
 *      but the Variables API is Enterprise-gated, so it may 403 without the right plan/scope.
 *   2. The checked-in snapshot `scripts/figma-variables.json` — refreshed via the Figma MCP
 *      (select the Colours foundation frame in Figma, re-pull, update the JSON).
 *
 * Only the PALETTE (raw, non-semantic ramps) is generated. The semantic layer
 * (colors.css), type scale (typography.css), and dimensions (tokens.css) are
 * hand-curated — they encode design decisions (which ramp step plays which role).
 */
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, '..');
const SNAPSHOT = join(HERE, 'figma-variables.json');
const OUT = join(ROOT, 'src/styles/palette.css');
const FILE_KEY = process.env.FIGMA_FILE_KEY || 'K94xaZYEFeZ0QQiqioY2RJ';

/** Figma variable name → palette token name (first match wins). */
const RULES = [
  [/^primary\/(\d00)$/, (m) => `red-${m[1]}`],
  [/^secondary\/(\d00)$/, (m) => `blue-${m[1]}`],
  [/^tertiary\/(\d00)$/, (m) => `magenta-${m[1]}`],
  [/^grey\/(\d00)$/, (m) => `grey-${m[1]}`],
  [/^base\/white$/, () => 'white'],
  [/^base\/black$/, () => 'black'],
  [/^gradient\/main\/stop-1$/, () => 'gradient-red'],
  [/^gradient\/main\/stop-3$/, () => 'gradient-magenta'],
  [/^gradient\/main\/stop-4$/, () => 'gradient-purple'],
];

const mapName = (figmaName) => {
  for (const [re, fn] of RULES) {
    const m = figmaName.match(re);
    if (m) return fn(m);
  }
  return null;
};

/** Output sections, in file order. */
const GROUPS = [
  { id: 'red', title: 'Primary — E.ON Red (Figma `primary/100…900`)' },
  { id: 'blue', title: 'Secondary — Blue (Figma `secondary/100…900`)' },
  { id: 'magenta', title: 'Tertiary — Magenta/Purple (Figma `tertiary/100…900`)' },
  { id: 'grey', title: 'Neutral — Grey (Figma `grey/100…900`)' },
  { id: 'base', title: 'Base' },
  { id: 'gradient', title: 'Brand gradient stops (Figma `gradient/main`)' },
];

const groupOf = (token) => {
  if (token === 'white' || token === 'black') return 'base';
  if (token.startsWith('gradient-')) return 'gradient';
  return token.split('-')[0];
};

/** Figma colour {r,g,b,a} (0..1) → #rrggbb (REST path). */
const rgbaToHex = ({ r, g, b }) => {
  const h = (n) => Math.round(n * 255).toString(16).padStart(2, '0');
  return `#${h(r)}${h(g)}${h(b)}`;
};

async function loadColors() {
  const token = process.env.FIGMA_TOKEN;
  if (token) {
    const res = await fetch(`https://api.figma.com/v1/files/${FILE_KEY}/variables/local`, {
      headers: { 'X-Figma-Token': token },
    });
    if (!res.ok) throw new Error(`Figma REST ${res.status}: ${await res.text()}`);
    const { meta } = await res.json();
    const colors = {};
    for (const v of Object.values(meta.variables ?? {})) {
      if (v.resolvedType !== 'COLOR') continue;
      const val = Object.values(v.valuesByMode ?? {})[0];
      if (!val || val.type === 'VARIABLE_ALIAS') continue; // skip unresolved aliases
      colors[v.name] = rgbaToHex(val);
    }
    return { source: 'Figma Variables REST API', colors };
  }
  const snap = JSON.parse(await readFile(SNAPSHOT, 'utf8'));
  return { source: 'snapshot (scripts/figma-variables.json)', colors: snap.colors };
}

function render(tokens, source) {
  const bySection = new Map(GROUPS.map((g) => [g.id, []]));
  for (const t of tokens) bySection.get(groupOf(t.token))?.push(t);

  let out = `/* ──────────────────────────────────────────────────────────────────────────
   palette.css — RAW, non-semantic colour ramps ("the ramp").

   ⚠️ AUTO-GENERATED by \`npm run sync:tokens\` from the E.ON Figma variables
   (source: ${source}). Do not edit by hand — change the variable in Figma and
   re-sync. The SEMANTIC layer (colors.css) is hand-curated and maps roles onto these.
   ────────────────────────────────────────────────────────────────────────── */
:root {
`;
  for (const g of GROUPS) {
    const items = bySection.get(g.id);
    if (!items?.length) continue;
    out += `  /* ${g.title} */\n`;
    for (const { token, value } of items) out += `  --${token}: ${value};\n`;
    out += '\n';
  }
  return out.replace(/\n+$/, '\n') + '}\n';
}

const { source, colors } = await loadColors();
const tokens = [];
const unmapped = [];
for (const [name, value] of Object.entries(colors)) {
  const token = mapName(name);
  if (token) tokens.push({ token, value });
  else unmapped.push(name);
}
await writeFile(OUT, render(tokens, source));
console.log(`sync:tokens — wrote ${tokens.length} colour tokens → src/styles/palette.css (source: ${source})`);
if (unmapped.length) console.log(`  skipped ${unmapped.length} unmapped variable(s): ${unmapped.join(', ')}`);
